"""Add line in, line out, and polygon

Revision ID: 24d2bdf8c3fe
Revises: cd4e408b7ea1
Create Date: 2025-06-18 13:21:57.705865

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '24d2bdf8c3fe'
down_revision = 'cd4e408b7ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('line_in', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('site', sa.Column('line_out', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('site', sa.Column('polygon', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'polygon')
    op.drop_column('site', 'line_out')
    op.drop_column('site', 'line_in')
    # ### end Alembic commands ###
