"""Add is_up column on item table

Revision ID: 391cf81fe82a
Revises: 805b7da4d7c6
Create Date: 2025-05-30 15:54:42.025645

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '391cf81fe82a'
down_revision = '805b7da4d7c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
