"""Remove address from site table

Revision ID: 64da49a9745c
Revises: 942fff0dd5cc
Create Date: 2025-06-18 15:08:12.126373

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '64da49a9745c'
down_revision = '942fff0dd5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
