"""Remove user's foreign key

Revision ID: 804ae1245ed1
Revises: 9a0eba6a2c3b
Create Date: 2025-07-17 17:06:59.760769

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '804ae1245ed1'
down_revision = '9a0eba6a2c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_region_owner_id_user'), 'region', type_='foreignkey')
    op.drop_column('region', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('region', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_region_owner_id_user'), 'region', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
