"""Make items table to store vehicle counting object data

Revision ID: 805b7da4d7c6
Revises: ff539b3e996d
Create Date: 2025-05-30 15:46:44.366815

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '805b7da4d7c6'
down_revision = 'ff539b3e996d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
