"""Refactor interval ping into sync interval and limit send into sync size

Revision ID: 85cf6decacbb
Revises: 64da49a9745c
Create Date: 2025-06-19 11:01:26.772785

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '85cf6decacbb'
down_revision = '64da49a9745c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hub', sa.Column('sync_interval', sa.Integer(), nullable=False))
    op.add_column('hub', sa.Column('sync_size', sa.Integer(), nullable=False))
    op.drop_column('hub', 'limit_send')
    op.drop_column('hub', 'interval_ping')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hub', sa.Column('interval_ping', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('hub', sa.Column('limit_send', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('hub', 'sync_size')
    op.drop_column('hub', 'sync_interval')
    # ### end Alembic commands ###
