"""Explode url into username, password, host, and port

Revision ID: 942fff0dd5cc
Revises: 24d2bdf8c3fe
Create Date: 2025-06-18 15:02:13.669222

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '942fff0dd5cc'
down_revision = '24d2bdf8c3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('site', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('site', sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('site', sa.Column('port', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('site', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('site', 'port')
    op.drop_column('site', 'host')
    op.drop_column('site', 'password')
    op.drop_column('site', 'username')
    # ### end Alembic commands ###
