"""Add region table

Revision ID: 9a0eba6a2c3b
Revises: 6a747dfa6d1b
Create Date: 2025-07-17 17:02:30.759878

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9a0eba6a2c3b'
down_revision = '6a747dfa6d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('line_in', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_out', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('polygon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_region_owner_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_region_site_id_site'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region')
    # ### end Alembic commands ###
