"""04 Add limit_send column into Hub table

Revision ID: b287531580e6
Revises: ea613b38e524
Create Date: 2025-06-04 09:15:37.835443

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b287531580e6'
down_revision = 'ea613b38e524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hub', sa.Column('limit_send', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hub', 'limit_send')
    # ### end Alembic commands ###
