"""Add track id, rename identity_index, and add track id

Revision ID: cd4e408b7ea1
Revises: d14f85e86e81
Create Date: 2025-06-18 10:27:28.313632

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cd4e408b7ea1'
down_revision = 'd14f85e86e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('id_track', sa.Integer(), nullable=False))
    op.add_column('item', sa.Column('id_cls', sa.Integer(), nullable=False))
    op.add_column('item', sa.Column('is_out', sa.Boolean(), nullable=False))
    op.drop_column('item', 'is_in')
    op.drop_column('item', 'entity_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('entity_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('is_in', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('item', 'is_out')
    op.drop_column('item', 'id_cls')
    op.drop_column('item', 'id_track')
    # ### end Alembic commands ###
