"""05 Rename ping_hub_interval column into interval_ping

Revision ID: d14f85e86e81
Revises: b287531580e6
Create Date: 2025-06-04 09:36:31.791421

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd14f85e86e81'
down_revision = 'b287531580e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hub', sa.Column('interval_ping', sa.Integer(), nullable=False))
    op.drop_column('hub', 'ping_hub_interval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hub', sa.Column('ping_hub_interval', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('hub', 'interval_ping')
    # ### end Alembic commands ###
