"""02 Make item table to store vehicle counting object data

Revision ID: dd4b86ff10da
Revises: ff539b3e996d
Create Date: 2025-06-03 13:59:07.939621

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd4b86ff10da'
down_revision = 'ff539b3e996d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('item', sa.Column('date_stamped', sa.DateTime(), nullable=False))
    op.add_column('item', sa.Column('entity_index', sa.Integer(), nullable=False))
    op.add_column('item', sa.Column('is_in', sa.Boolean(), nullable=False))
    op.add_column('item', sa.Column('is_up', sa.Boolean(), nullable=False))
    op.drop_column('item', 'description')
    op.drop_column('item', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('item', 'is_up')
    op.drop_column('item', 'is_in')
    op.drop_column('item', 'entity_index')
    op.drop_column('item', 'date_stamped')
    op.drop_column('item', 'date_created')
    # ### end Alembic commands ###
