"""03 Refactor url column into host and port columns

Revision ID: ea613b38e524
Revises: dd4b86ff10da
Create Date: 2025-06-04 09:08:33.816912

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea613b38e524'
down_revision = 'dd4b86ff10da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hub', sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('hub', sa.Column('port', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('hub', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hub', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('hub', 'port')
    op.drop_column('hub', 'host')
    # ### end Alembic commands ###
